/*
 * Copyright 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import UsbServerTypes;
sequenceable OHOS.IRemoteObject;
sequenceable UsbDevice..OHOS.USB.UsbDevice;
sequenceable UsbAccessory..OHOS.USB.USBAccessory;
sequenceable UsbPort..OHOS.USB.UsbPort;
sequenceable UsbEndpoint..OHOS.USB.USBEndpoint;
sequenceable UsbSerialType..OHOS.USB.UsbSerialPort;
sequenceable UsbSerialType..OHOS.USB.UsbSerialAttr;
sequenceable UsbBulkTransData..OHOS.USB.UsbBulkTransData;

interface OHOS.USB.IUsbServer {
    /* the function about UsbService */
    [macrodef USB_MANAGER_FEATURE_HOST] void GetDevices([out]UsbDevice[] deviceList);
    [macrodef USB_MANAGER_FEATURE_HOST] void OpenDevice([in]unsigned char busNum, [in]unsigned char devAddr);
    [macrodef USB_MANAGER_FEATURE_HOST] void Close([in]unsigned char busNum, [in]unsigned char devAddr);
    [macrodef USB_MANAGER_FEATURE_HOST] void ResetDevice([in]unsigned char busNum, [in]unsigned char devAddr);
    [macrodef USB_MANAGER_FEATURE_HOST] void ClaimInterface([in]unsigned char busNum, [in]unsigned char devAddr, [in]unsigned char interfaceid, [in]unsigned char force);
    [macrodef USB_MANAGER_FEATURE_HOST] void SetInterface([in]unsigned char busNum, [in]unsigned char devAddr, [in]unsigned char interfaceid, [in]unsigned char altIndex);
    [macrodef USB_MANAGER_FEATURE_HOST] void ReleaseInterface([in]unsigned char busNum, [in]unsigned char devAddr, [in]unsigned char interfaceid);
    [macrodef USB_MANAGER_FEATURE_HOST] void SetActiveConfig([in]unsigned char busNum, [in]unsigned char devAddr, [in]unsigned char configId);
    [macrodef USB_MANAGER_FEATURE_HOST] void ManageGlobalInterface([in]boolean disable);
    [macrodef USB_MANAGER_FEATURE_HOST] void ManageDevice([in]int vendorId, [in]int productId, [in]boolean disable);
    [macrodef USB_MANAGER_FEATURE_HOST] void ManageInterfaceType([in]UsbDeviceTypeInfo[] disableType, [in]boolean disable);
    [macrodef USB_MANAGER_FEATURE_HOST] void UsbAttachKernelDriver([in]unsigned char busNum, [in]unsigned char devAddr, [in]unsigned char interfaceid);
    [macrodef USB_MANAGER_FEATURE_HOST] void UsbDetachKernelDriver([in]unsigned char busNum, [in]unsigned char devAddr, [in]unsigned char interfaceid);
    [macrodef USB_MANAGER_FEATURE_HOST] void ClearHalt([in]unsigned char busNum, [in]unsigned char devAddr, [in]unsigned char interfaceid, [in]unsigned char endpointId);
    [macrodef USB_MANAGER_FEATURE_HOST] void GetActiveConfig([in]unsigned char busNum, [in]unsigned char devAddr, [out]unsigned char configId);
    [macrodef USB_MANAGER_FEATURE_HOST] void GetRawDescriptor([in]unsigned char busNum, [in]unsigned char devAddr, [out]unsigned char[] bufferData);
    [macrodef USB_MANAGER_FEATURE_HOST] void GetFileDescriptor([in]unsigned char busNum, [in]unsigned char devAddr, [out]FileDescriptor fd);
    [macrodef USB_MANAGER_FEATURE_HOST] void GetDeviceSpeed([in]unsigned char busNum, [in]unsigned char devAddr, [out]unsigned char speed);
    [macrodef USB_MANAGER_FEATURE_HOST] void GetInterfaceActiveStatus([in]unsigned char busNum, [in]unsigned char devAddr, [in]unsigned char interfaceid, [out]boolean unactivated);
    [macrodef USB_MANAGER_FEATURE_HOST] void BulkTransferRead([in]unsigned char busNum, [in]unsigned char devAddr, [in]USBEndpoint ep, [out]UsbBulkTransData buffData, [in]int timeOut);
    [macrodef USB_MANAGER_FEATURE_HOST] void BulkTransferWrite([in]unsigned char busNum, [in]unsigned char devAddr, [in]USBEndpoint ep, [in]UsbBulkTransData buffData, [in]int timeOut);
    [macrodef USB_MANAGER_FEATURE_HOST] void BulkTransferReadwithLength([in]unsigned char busNum, [in]unsigned char devAddr, [in]USBEndpoint ep, [in]int length, [out]UsbBulkTransData buffData, [in]int timeOut);
    [macrodef USB_MANAGER_FEATURE_HOST] void ControlTransfer([in]unsigned char busNum, [in]unsigned char devAddr, [in]UsbCtlSetUp ctrlParams, [inout]unsigned char[] bufferData);
    [macrodef USB_MANAGER_FEATURE_HOST] void UsbControlTransfer([in]unsigned char busNum, [in]unsigned char devAddr, [in]UsbCtlSetUp ctrlParams, [inout]unsigned char[] bufferData);
    [macrodef USB_MANAGER_FEATURE_HOST] void RequestQueue([in]unsigned char busNum, [in]unsigned char devAddr, [in]USBEndpoint ep, [in]unsigned char[] clientData, [in]unsigned char[] bufferData);
    [macrodef USB_MANAGER_FEATURE_HOST] void RequestWait([in]unsigned char busNum, [in]unsigned char devAddr, [in]int timeOut, [inout]unsigned char[] clientData, [inout]unsigned char[] bufferData);
    [macrodef USB_MANAGER_FEATURE_HOST] void RequestCancel([in]unsigned char busNum, [in]unsigned char devAddr, [in]unsigned char interfaceid, [in]unsigned char endpointId);
    [macrodef USB_MANAGER_FEATURE_HOST] void UsbCancelTransfer([in]unsigned char busNum, [in]unsigned char devAddr, [in]int endpoint);
    [macrodef USB_MANAGER_FEATURE_HOST] void UsbSubmitTransfer([in]unsigned char busNum, [in]unsigned char devAddr, [in]UsbTransInfo info, [in]IRemoteObject cb, [in]FileDescriptor fd, [in] int memSize);
    [macrodef USB_MANAGER_FEATURE_HOST] void RegBulkCallback([in]unsigned char busNum, [in]unsigned char devAddr, [in]USBEndpoint ep, [in]IRemoteObject cb);
    [macrodef USB_MANAGER_FEATURE_HOST] void UnRegBulkCallback([in]unsigned char busNum, [in]unsigned char devAddr, [in]USBEndpoint ep);
    [macrodef USB_MANAGER_FEATURE_HOST] void BulkRead([in]unsigned char busNum, [in]unsigned char devAddr, [in]USBEndpoint ep, [in]FileDescriptor ashmem, [in] int memSize);
    [macrodef USB_MANAGER_FEATURE_HOST] void BulkWrite([in]unsigned char busNum, [in]unsigned char devAddr, [in]USBEndpoint ep, [in]FileDescriptor ashmem, [in] int memSize);
    [macrodef USB_MANAGER_FEATURE_HOST] void BulkCancel([in]unsigned char busNum, [in]unsigned char devAddr, [in]USBEndpoint ep);
    [macrodef USB_MANAGER_FEATURE_HOST] void HasRight([in]String deviceName, [out]boolean hasRight);
    [macrodef USB_MANAGER_FEATURE_HOST] void RequestRight([in]String deviceName);
    [macrodef USB_MANAGER_FEATURE_HOST] void RemoveRight([in]String deviceName);
    [macrodef USB_MANAGER_FEATURE_HOST] void AddRight([in]String bundleName, [in]String deviceName);
    [macrodef USB_MANAGER_FEATURE_HOST] void AddAccessRight([in]String tokenId, [in]String deviceName);

    [macrodef USB_MANAGER_FEATURE_DEVICE] void GetCurrentFunctions([out] int funcs);
    [macrodef USB_MANAGER_FEATURE_DEVICE] void SetCurrentFunctions([in] int funcs);
    [macrodef USB_MANAGER_FEATURE_DEVICE] int UsbFunctionsFromString([in] String funcs);
    [macrodef USB_MANAGER_FEATURE_DEVICE] String UsbFunctionsToString([in] int funcs);
    [macrodef USB_MANAGER_FEATURE_DEVICE] void AddAccessoryRight([in] unsigned int tokenId, [in] USBAccessory access);
    [macrodef USB_MANAGER_FEATURE_DEVICE] void HasAccessoryRight([in] USBAccessory access, [out] boolean checkResult);
    [macrodef USB_MANAGER_FEATURE_DEVICE] void RequestAccessoryRight([in] USBAccessory access, [out] boolean checkResult);
    [macrodef USB_MANAGER_FEATURE_DEVICE] void CancelAccessoryRight([in] USBAccessory access);
    [macrodef USB_MANAGER_FEATURE_DEVICE] void GetAccessoryList([out] USBAccessory[] accessList);
    [macrodef USB_MANAGER_FEATURE_DEVICE] void OpenAccessory([in] USBAccessory access, [out] FileDescriptor fd);
    [macrodef USB_MANAGER_FEATURE_DEVICE] void CloseAccessory([in] int fd);

    [macrodef USB_MANAGER_FEATURE_PORT] void GetPorts([out]UsbPort[] ports);
    [macrodef USB_MANAGER_FEATURE_PORT] void GetSupportedModes([in] int portId, [out] int supportedModes);
    [macrodef USB_MANAGER_FEATURE_PORT] void SetPortRole([in] int portId, [in] int powerRole, [in] int dataRole);

    void SerialOpen([in] int portId, [in] IRemoteObject serialRemote);
    void SerialClose([in] int portId);
    void SerialRead([in] int portId, [out]unsigned char[] buffData, [in]unsigned int size, [out]unsigned int actualSize, [in]unsigned int timeout);
    void SerialWrite([in] int portId, [in]unsigned char[] buffData, [in]unsigned int size, [out]unsigned int actualSize, [in]unsigned int timeout);
    void SerialGetAttribute([in] int portId, [out]UsbSerialAttr attribute);
    void SerialSetAttribute([in] int portId, [in]UsbSerialAttr attribute);
    void SerialGetPortList([out] UsbSerialPort[] serialPortList);
    void AddSerialRight([in] unsigned int tokenId, [in] int portId);
    void HasSerialRight([in] int portId, [out]boolean hasRight);
    void RequestSerialRight([in] int portId, [out]boolean hasRight);
    void CancelSerialRight([in] int portId);
}